site_name: Jerry's Knowledge Base
site_url: https://freecow.github.io
repo_url: https://github.com/freecow/freecow.github.io
repo_name: freecow/freecow.github.io
edit_uri: edit/main/docs/
strict: true

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.path
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.prune
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Light Mode
  font:
    text: Noto Sans SC
    code: JetBrains Mono
  language: zh
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
plugins:
  - search
  - tags
  - social
  - meta-descriptions
  - blog:
      blog_dir: 随笔
      blog_toc: true
      draft_on_serve: false
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css
copyright: Copyright &copy; 2025 GeniusX
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true

# 如果部署到子目录，需要设置
site_dir: site
